# @package _global_

use_wandb: True

wandb:
  wandb_project: null
  wandb_tags: 'online' # 'online' or 'offline' or 'disabled'
  wandb_group: zixinzhang
  wandb_id: null
  wandb_entity: zixinzhang
  wandb_dir: ${experiment_dir}/.wandb