ROBOT_TYPE: 'g1_29dof' # Robot name, "t1_23dof", "g1_29dof", "go2", "b2", "b2w", "h1", "go2w"
ROBOT_SCENE: "../humanoidverse/data/robots/g1/scene_g1_29dof_freebase.xml" # Robot scene, for Sim2Sim
ASSET_ROOT: "../humanoidverse/data/robots/g1" # Robot Asset Root
ASSET_FILE: "../humanoidverse/data/robots/g1/g1_29dof.urdf" # Robot Asset File"

# Model path for the trained policy
model_path: "models/falcon/g1_29dof.onnx"

SDK_TYPE: "unitree" # SDK type, "unitree", "booster"
MOTOR_TYPE: "serial" # Motor type, "serial" or "parallel"

## SIM
DOMAIN_ID: 0 # Domain id
INTERFACE: "lo" # in simulation, lo0 for mac, lo for linux

FREE_BASE: True

PRINT_SCENE_INFORMATION: True # Print link, joint and sensors information of robot
ENABLE_ELASTIC_BAND: True # Virtual spring band, used for lifting h1

SIMULATE_DT: 0.005  # Need to be larger than the runtime of viewer.sync()
VIEWER_DT: 0.02  # Viewer update time
USE_SENSOR: False

USE_JOYSTICK: 0 # Simulate Unitree WirelessController using a gamepad (0: disable, 1: enable)
JOYSTICK_TYPE: "xbox" # support "xbox" and "switch" gamepad layout
JOYSTICK_DEVICE: 0 # Joystick number

VISUALIZE_PIN: False
VISUALIZE_FORCES: False

residual_upper_body_action: True # Whether to use residual upper body action for balancing
use_upper_body_controller: False # Whether to use upper body controller

GAIT_PERIOD: 0.9 # Gait period in seconds
DESIRED_BASE_HEIGHT: 0.75 # Desired base height

MOTOR2JOINT: [0, 1, 2, 3, 4, 5,
              6, 7, 8, 9, 10, 11,
              12, 13, 14, 
              15, 16, 17, 18, 19, 20, 21, 
              22, 23, 24, 25, 26, 27, 28]
            
JOINT2MOTOR: [0, 1, 2, 3, 4, 5,
              6, 7, 8, 9, 10, 11,
              12, 13, 14, 
              15, 16, 17, 18, 19, 20, 21, 
              22, 23, 24, 25, 26, 27, 28]
            

UNITREE_LEGGED_CONST:
  HIGHLEVEL: 0xEE
  LOWLEVEL: 0xFF
  TRIGERLEVEL: 0xF0
  PosStopF: 2146000000.0
  VelStopF: 16000.0
  MODE_MACHINE: 5
  MODE_PR:  0

JOINT_KP: [
    100, 100, 100, 200, 20, 20,
    100, 100, 100, 200, 20, 20,
    300, 300, 300,
    90, 60, 20, 60, 4, 4, 4,
    90, 60, 20, 60, 4, 4, 4
]

JOINT_KD: [
   2.5, 2.5, 2.5, 5, 0.2, 0.1,
   2.5, 2.5, 2.5, 5, 0.2, 0.1,
   5.0, 5.0, 5.0,
   2.0, 1.0, 0.4, 1.0, 0.2, 0.2, 0.2,
    2.0, 1.0, 0.4, 1.0, 0.2, 0.2, 0.2
]

MOTOR_KP: [
    100, 100, 100, 200, 20, 20,
    100, 100, 100, 200, 20, 20,
    300, 300, 300,
    90, 60, 20, 60, 4, 4, 4,
    90, 60, 20, 60, 4, 4, 4
]

MOTOR_KD: [
   2.5, 2.5, 2.5, 5, 0.2, 0.1,
   2.5, 2.5, 2.5, 5, 0.2, 0.1,
   5.0, 5.0, 5.0,
   2.0, 1.0, 0.4, 1.0, 0.2, 0.2, 0.2,
    2.0, 1.0, 0.4, 1.0, 0.2, 0.2, 0.2
]

dof_names: ['left_hip_yaw_joint', 'left_hip_roll_joint', 'left_hip_pitch_joint', 
            'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint',
            'right_hip_yaw_joint', 'right_hip_roll_joint', 'right_hip_pitch_joint',
            'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint',
            'waist_yaw_joint', 'waist_roll_joint', 'waist_pitch_joint',
            'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 
            'left_shoulder_yaw_joint', 'left_elbow_joint',
            'left_wrist_roll_joint', 'left_wrist_pitch_joint', 
            'left_wrist_yaw_joint',
            'right_shoulder_pitch_joint', 'right_shoulder_roll_joint',
            'right_shoulder_yaw_joint', 'right_elbow_joint',
            'right_wrist_roll_joint', 'right_wrist_pitch_joint',
            'right_wrist_yaw_joint']
dof_names_upper_body: ['left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 
                      'left_shoulder_yaw_joint', 'left_elbow_joint',
                      'left_wrist_roll_joint', 'left_wrist_pitch_joint', 'left_wrist_yaw_joint',
                      'right_shoulder_pitch_joint', 'right_shoulder_roll_joint',
                      'right_shoulder_yaw_joint', 'right_elbow_joint',
                      'right_wrist_roll_joint', 'right_wrist_pitch_joint', 'right_wrist_yaw_joint']
dof_names_lower_body: ['left_hip_yaw_joint', 'left_hip_roll_joint', 'left_hip_pitch_joint',
                      'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint',
                      'right_hip_yaw_joint', 'right_hip_roll_joint', 'right_hip_pitch_joint',
                      'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint',
                      'waist_yaw_joint', 'waist_roll_joint', 'waist_pitch_joint']
left_hand_link_name: "left_rubber_hand"
right_hand_link_name: "right_rubber_hand"
WeakMotorJointIndex:
  left_hip_yaw_joint: 0
  left_hip_roll_joint: 1
  left_hip_pitch_joint: 2
  left_knee_joint: 3
  left_ankle_pitch_joint: 4
  left_ankle_roll_joint: 5
  right_hip_yaw_joint: 6
  right_hip_roll_joint: 7
  right_hip_pitch_joint: 8
  right_knee_joint: 9
  right_ankle_pitch_joint: 10
  right_ankle_roll_joint: 11
  waist_yaw_joint : 12
  waist_roll_joint : 13
  waist_pitch_joint : 14
  left_shoulder_pitch_joint: 15
  left_shoulder_roll_joint: 16
  left_shoulder_yaw_joint: 17
  left_elbow_joint: 18
  left_wrist_roll_joint: 19
  left_wrist_pitch_joint: 20
  left_wrist_yaw_joint: 21
  right_shoulder_pitch_joint: 22
  right_shoulder_roll_joint: 23
  right_shoulder_yaw_joint: 24
  right_elbow_joint: 25
  right_wrist_roll_joint: 26
  right_wrist_pitch_joint: 27
  right_wrist_yaw_joint: 28

NUM_MOTORS: 29
NUM_JOINTS: 29
NUM_UPPER_BODY_JOINTS: 14

DEFAULT_DOF_ANGLES: [
    -0.1,  # left_hip_pitch_joint 
    0.0,  # left_hip_roll_joint
    0.0,  # left_hip_yaw_joint
    0.3,  # left_knee_joint
    -0.2, # left_ankle_pitch_joint
    0.0,  # left_ankle_roll_joint
    -0.1, # right_hip_pitch_joint
    0.0,  # right_hip_roll_joint
    0.0,  # right_hip_yaw_joint
    0.3,  # right_knee_joint
    -0.2, # right_ankle_pitch_joint
    0.0,  # right_ankle_roll_joint
    0.0,  # waist_yaw_joint
    0.0,  # waist_roll_joint
    0.0,  # waist_pitch_joint
    0.0,  # left_shoulder_pitch_joint
    0.0,  # left_shoulder_roll_joint
    0.0,  # left_shoulder_yaw_joint
    0.0,  # left_elbow_joint
    0.0,  # left_wrist_roll_joint
    0.0,  # left_wrist_pitch_joint
    0.0,  # left_wrist_yaw_joint
    0.0,  # right_shoulder_pitch_joint
    0.0,  # right_shoulder_roll_joint
    0.0,  # right_shoulder_yaw_joint
    0.0,  # right_elbow_joint
    0.0,  # right_wrist_roll_joint
    0.0,  # right_wrist_pitch_joint
    0.0   # right_wrist_yaw_joint
]

DEFAULT_MOTOR_ANGLES: [
    -0.1,  # left_hip_pitch_joint 
    0.0,  # left_hip_roll_joint
    0.0,  # left_hip_yaw_joint
    0.3,  # left_knee_joint
    -0.2, # left_ankle_pitch_joint
    0.0,  # left_ankle_roll_joint
    -0.1, # right_hip_pitch_joint
    0.0,  # right_hip_roll_joint
    0.0,  # right_hip_yaw_joint
    0.3,  # right_knee_joint
    -0.2, # right_ankle_pitch_joint
    0.0,  # right_ankle_roll_joint
    0.0,  # waist_yaw_joint
    0.0,  # waist_roll_joint
    0.0,  # waist_pitch_joint
    0.0,  # left_shoulder_pitch_joint
    0.0,  # left_shoulder_roll_joint
    0.0,  # left_shoulder_yaw_joint
    0.0,  # left_elbow_joint
    0.0,  # left_wrist_roll_joint
    0.0,  # left_wrist_pitch_joint
    0.0,  # left_wrist_yaw_joint
    0.0,  # right_shoulder_pitch_joint
    0.0,  # right_shoulder_roll_joint
    0.0,  # right_shoulder_yaw_joint
    0.0,  # right_elbow_joint
    0.0,  # right_wrist_roll_joint
    0.0,  # right_wrist_pitch_joint
    0.0   # right_wrist_yaw_joint
]

motor_pos_lower_limit_list: [-2.5307, -0.5236, -2.7576, -0.087267, -0.87267, -0.2618, 
                             -2.5307, -2.9671, -2.7576, -0.087267, -0.87267, -0.2618, 
                             -2.618, -0.52, -0.52,
                             -3.0892, -1.5882, -2.618, -1.0472, 
                             -1.972222054, -1.61443, -1.61443,
                             -3.0892, -2.2515, -2.618, -1.0472, 
                             -1.972222054, -1.61443, -1.61443]
motor_pos_upper_limit_list: [2.8798, 2.9671, 2.7576, 2.8798, 0.5236, 0.2618, 
                            2.8798, 0.5236, 2.7576, 2.8798, 0.5236, 0.2618, 
                            2.618, 0.52, 0.52,
                            2.6704, 2.2515, 2.618, 2.0944, 
                            1.972222054, 1.61443, 1.61443,
                            2.6704, 1.5882, 2.618, 2.0944, 
                            1.972222054, 1.61443, 1.61443]
motor_vel_limit_list: [32.0, 32.0, 32.0, 20.0, 37.0, 37.0, 
                      32.0, 32.0, 32.0, 20.0, 37.0, 37.0, 
                      32.0, 37.0, 37.0, 
                      37.0, 37.0, 37.0, 37.0, 
                      37.0, 22.0, 22.0,
                      37.0, 37.0, 37.0, 37.0, 
                      37.0, 22.0, 22.0]
motor_effort_limit_list: [88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 
                        88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 
                        88.0, 50.0, 50.0,
                        25.0, 25.0, 25.0, 25.0, 
                        25.0, 5.0, 5.0,
                        25.0, 25.0, 25.0, 25.0, 
                        25.0, 5.0, 5.0]
obs_dict: {
  actor_obs: [
    base_ang_vel,
    projected_gravity,
    command_lin_vel,
    command_ang_vel,
    command_stand,
    command_base_height,
    command_waist_dofs,
    ref_upper_dof_pos,
    dof_pos,
    dof_vel,
    actions,
  ],
}
history_length_dict: {
  actor_obs: 5,
}
obs_dims: {
            base_lin_vel: 3,
            base_ang_vel: 3,
            projected_gravity: 3,
            command_lin_vel: 2,
            command_ang_vel: 1,
            command_stand: 1,
            command_base_height: 1,
            command_waist_dofs: 3,
            ref_upper_dof_pos: 14, # upper body actions
            dof_pos: 29,
            dof_vel: 29,
            actions: 29, # lower body actions
            phase_time: 1,
          }
obs_scales: {
    base_lin_vel: 2.0,
    base_ang_vel: 0.25,
    projected_gravity: 1.0,
    command_lin_vel: 1.0,
    command_ang_vel: 1.0,
    command_stand: 1.0,
    command_base_height: 2.0,
    command_waist_dofs: 1.0,
    ref_upper_dof_pos: 1.0,
    dof_pos: 1.0,
    dof_vel: 0.05,
    history: 1.0,
    actions: 1.0,
    phase_time: 1.0,
  }